Repository infinitepixel-dev/InfinitePixel-Main, pull requests merged in 2025-04, with the labels that each got.

#160 Contact Form Animation & Link Handling Fix
  src/components/ContactForm.jsx
  src/components/Navbar.jsx
  src/components/Review.jsx
  src/components/pages/Portfolio.jsx
Labels: bug, ui

#161 InfinitePixel Website – UI Animation, Contact Form Fixes & Portfolio Enhancements
  .eslintrc.cjs
  package-lock.json
  package.json
  public/images/barber.png
  public/images/wave-haikei.svg
  src/App.jsx
  src/components/ContactForm.jsx
  src/components/CustomCursor.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/Review.jsx
  src/components/breakpoints.jsx
  src/components/buttons/actionButton.jsx
  src/components/corecomponents/Api-testing.jsx
  src/components/corecomponents/home.css
  src/components/corecomponents/home.jsx
  src/components/corecomponents/navigationBar.css
  src/components/corecomponents/navigationBar.jsx
  src/components/corecomponents/siteRoutes.jsx
  src/components/documentation/developerDocs.jsx
  src/components/effects/animations/fadeIn.jsx
  src/components/effects/customCursor.jsx
  src/components/menus/aboutUs-Carousel.jsx
  src/components/menus/carousel-with-buttons.jsx
  src/components/pages/Login/login.jsx
  src/components/pages/Payments/payments.jsx
  src/components/pages/Portfolio.jsx
  src/components/pages/SplashPage/splashPage.css
  src/components/pages/SplashPage/splashPage.jsx
  src/components/pages/payments.jsx
  src/components/utility/ScrollingIconsBar.jsx
  src/context/navigationContext.jsx
  src/dynamicComponentLoader.jsx
  vite.config.js
Labels: bug, enhancement, ui, refactor

#163 bugfix: removed crypto dep.
  pnpm-lock.yaml
Labels: bug

#169 animation logic in contact form
  src/components/ContactForm.jsx
  src/components/WhatWeDo.jsx
Labels: tweak

#170 updated contact gradient bg
  src/components/ContactForm.jsx
Labels: tweak

#177 v1.2.2 - refactor file paths throughout app, removed unused components and data
  src/App.jsx
  src/components/pages/AboutUs/aboutUs.jsx
  src/components/pages/Footer/footer.jsx
  src/components/pages/HeroPage/heroBackground.jsx
  src/components/pages/HeroPage/heroPage.jsx
  src/components/pages/HeroPage/services.jsx
  src/components/website/Footer.jsx
  src/components/website/Header.jsx
  src/components/website/Navbar.jsx
  src/components/website/cards/Map.jsx
  src/components/website/cards/Review.jsx
  src/components/website/pages/AboutUs.jsx
  src/components/website/pages/ContactForm.jsx
  src/components/website/pages/Portfolio.jsx
  src/components/website/pages/WhatWeDo.jsx
  src/components/website/utilities/ScrollingIconsBar.jsx
  src/componentsIndex.jsx
  src/componentsRegistry.jsx
  src/dynamicComponentLoader.jsx
  vite.config.js
Labels: refactor, tweak

#181 added logo small png to images
  pnpm-lock.yaml
  public/images/logo_small.png
Labels: tweak

#195 ui: updated app logo for google search
  index.html
  public/images/logo.ico
Labels: ui

#216 refactor: updated ADA/WCAG compliance on navbar and portfolio page.
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/website/Navbar.jsx
  src/components/website/pages/Portfolio.jsx
  src/components/website/utilities/AccessibleIcon.jsx
  src/main.jsx
Labels: refactor

#230 ui: contact page layout changes
  src/components/website/pages/AboutUs.jsx
  src/components/website/pages/ContactForm.jsx
Labels: ui
